apiVersion: v1
kind: Template
labels:
  template: couchdb-ephemeral-template
message: |-
  The following service(s) have been created in your project: ${COUCHDB_SERVICE_NAME}.

   Connection URL: http://${COUCHDB_SERVICE_NAME}:5984/
metadata:
  annotations:
    description: |-
      Couchdb database service, without persistent storage.

      WARNING: Any data stored will be lost upon pod destruction. Only use this template for testing
    openshift.io/display-name: CouchDB (Ephemeral)
    tags: database,couchdb
    template.openshift.io/documentation-url: http://docs.couchdb.org/en/1.6.1/
    template.openshift.io/long-description: This template provides a standalone CouchDB
      server with a database created.  The database is not stored on persistent storage,
      so any restart of the service will result in all data being lost.
    template.openshift.io/provider-display-name: SDP Team
    template.openshift.io/support-url: https://svcmgr.cdc.gov/
  creationTimestamp: null
  name: couchdb-ephemeral
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: '${COUCHDB_SERVICE_NAME}'
  stringData:
    database-user: '${COUCHDB_USER}'
    database-password: '${COUCHDB_PASSWORD}'
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: '${COUCHDB_SERVICE_NAME}'
  spec:
    ports:
    - name: couch
      protocol: TCP
      port: 5984
      targetPort: 5984
    selector:
      name: '${COUCHDB_SERVICE_NAME}'
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    name: '${COUCHDB_SERVICE_NAME}'
  spec:
    replicas: 1
    selector:
      name: '${COUCHDB_SERVICE_NAME}'
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: '${COUCHDB_SERVICE_NAME}'
      spec:
        containers:
        - capabilities: {}
          env:
          - name: COUCHDB_USER
            valueFrom: {secretKeyRef: {name: '${COUCHDB_SERVICE_NAME}', key: database-user}}
          - name: COUCHDB_PASSWORD
            valueFrom: {secretKeyRef: {name: '${COUCHDB_SERVICE_NAME}', key: database-password}}
          image: ' '
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5984
            timeoutSeconds: 1
          name: couchdb
          ports:
          - containerPort: 5984
            protocol: TCP
          readinessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 5984
            timeoutSeconds: 1
          resources:
            limits:
              memory: ${MEMORY_LIMIT}
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /usr/local/var/lib/couchdb
            name: '${COUCHDB_SERVICE_NAME}-data'
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
            medium: ''
          name: '${COUCHDB_SERVICE_NAME}-data'
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - couchdb
        from:
          kind: ImageStreamTag
          name: ${COUCHDB_IMAGE}:${COUCHDB_VERSION}
          namespace: ${NAMESPACE}
        lastTriggerImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}
parameters:
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  required: true
  value: 512Mi
- name: NAMESPACE
  displayName: Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
- name: COUCHDB_SERVICE_NAME
  displayName: CouchDB Service Name
  description: The name of the OpenShift Service exposed for this instance.
  required: true
  value: couchdb
- name: COUCHDB_IMAGE
  displayName: CouchDB Image Name
  description: The name of the CouchDB ImageStream to be used.
  required: true
  value: ocp-couchdb
- name: COUCHDB_VERSION
  displayName: Version of the CouchDB Image
  description: Version of the CouchDB image to be used (1.6 or latest)
  required: true
  value: "1.6"
- name: COUCHDB_USER
  displayName: CouchDB Connection Username
  description: Username for the CouchDB user that will be used for accessing the database.
  generate: expression
  from: 'user[A-Z0-9]{3}'
  required: true
- name: COUCHDB_PASSWORD
  displayName: CouchDB Connection Password
  description: Password for the CouchDB connection user.
  generate: expression
  from: '[a-zA-Z0-9]{16}'
  required: true
